Feature/add dynamic tests
SleeplessByte/media-types-ruby pull request #92
Opened 2020-08-09 17:30 UTC by louisraymond

2020-08-10 21:38 UTC, SleeplessByte commented on README.md
> +      class AnyType
Can we not indent this?

2020-08-10 21:45 UTC, SleeplessByte commented on README.md
> +          execute_assertions(AnyType)
I think we really need to give the user of the library a chance to call this _whenever_ they want. So this works, but makes the file crash _on load_, which isn't ideal, because it may not be when the server starts. Instead, let's define an extra method on the generated `AnyType`, like `#assert_sane!`, which basically does: `execute_assertions(self.class)`.

Then, we **automatically** call this function on the first `validate!`, if it has not ran yet.
Thirdly, add a custom `assert_media_type AnyType` function, which runs all the asserts in a minitest context.

Ideally, we would want a test to be generated dynamically, but if `#assert_sane!` is implemented correctly, and `assert_media_type Type` works, a media type test for a library could look like:

```ruby
class MyMediaTypeTest < BaseTest

  [My, Media, Type, Array].each do |type|
    define_method "test_#{type.name}_media_type_sanity" do
      assert_media_type type
    end
  end
end
```

If this is the case, we can just document it and not generate anything, and/or supply `rails generator` for this.

2020-08-10 21:46 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @fixtures=[]
Please white-space consistently.

2020-08-10 21:46 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        {fixture: fixture,
Please white-space consistently

2020-08-10 21:47 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        begin
This shouldn't be indented the extra 2 spaces

2020-08-10 21:49 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @errors << "Fixture: #{json} expected to fail validation check in #{media_type_class}, but it did not" if expectation_met == false
Don't add "string" errors, but instead, use a new error klazz.

2020-08-10 21:49 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        @errors << "Fixture: #{json} expected to pass validation check in #{media_type_class}, but it did not" if expectation_met == false
Don't add "string" errors, but instead, use a new error klazz.
We probably want to _enclose_ the validation error, so we can show "this is the input, this is the error".

2020-08-10 21:51 UTC, SleeplessByte commented
When you're done with the next version, please provide the output for 

```shell
rake test
```

2020-08-12 17:10 UTC, louisraymond commented on README.md
> +          execute_assertions(AnyType)
Do you mean write a method called assert_sane! in the MediaTypes::Dsl module? Because giving AnyType would mean that we would have to hard code the same method in every fixture/media_type we create. I don't fully understand the advantage of this if assert_sane! and execute_assertions are going to contain the same logic? I think I am missing something that you are seeing.
Perhaps you mean that the execute_assertions method is fine, but it's not good to actually have it placed so that it runs in the class, because then it will run on load, instead you want a method that kind of wraps around this, and lets users add logic for when the asserts should be executed??
There is a small problem with using self.class (which is why I didn't use it for execute_assertions), which is that at the location the asserts are called , self refers to an instance of Validations. This is why I think the class has to be explicitly given to the Assert function (AnyType) for instance.

2020-08-12 17:17 UTC, louisraymond commented on README.md
> +          execute_assertions(AnyType)
Ah, perhaps you mean that we want a method `assert_sane!` that is going to be callable from where `execute_assertions` goes now, but automatically would know what the class is

2020-08-12 22:10 UTC, SleeplessByte commented on README.md
> +          execute_assertions(AnyType)
`assert_sane!` should be available on _any_ media type, and shouldn't be duplicated by a user using our library. Otherwise, we wouldn't be able to _automatically_ call it (or it would break all the time if a user had not defined it themselves). 

> Perhaps you mean that the execute_assertions method is fine, but it's not good to actually have it placed so that it runs in the class, because then it will run on load, instead you want a method that kind of wraps around this, and lets users add logic for when the asserts should be executed??

Right now it runs on file load, which, as written, is probably not what we want.

> self refers to an instance of Validations.

You need to traverse the _ancestors_ until you get to the media type class itself.

> Ah, perhaps you mean that we want a method assert_sane! that is going to be callable from where execute_assertions goes now, but automatically would know what the class is

I definitely want `assert_sane!` to know what class it is; `execute_assertions` should probably know which class it is as well -- but implement it as you see fit.

2020-08-19 02:46 UTC, SleeplessByte requested changes

2020-08-19 02:46 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @errors << "Fixture: #{json} expected to fail validation check in #{media_type_class}, but it did not" if expectation_met == false
No resolved

2020-08-19 02:46 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise AssertionError, @errors.map { |error| error.msg } if !@errors.empty?
```suggestion
      raise AssertionError, @errors.map { |error| error.msg } unless @errors.empty?
```

2020-08-19 02:46 UTC, SleeplessByte commented on test/test_helper.rb
> +  def assert_media_type(media_type)
This doesn't make this method available to _libraries_ using this gem.

2020-08-19 02:46 UTC, SleeplessByte commented on README.md
> +
Missing information when execute_assertions is called, if ever. Manual is clear, but if not called manual, what happens?

2020-08-19 02:58 UTC, louisraymond commented on README.md
> +
Just updated the readme

2020-08-19 03:24 UTC, louisraymond commented on test/test_helper.rb
> +  def assert_media_type(media_type)
I moved this to `assert_media_type_format.rb` which seems a logical place for it. However the file is named after the single method it used to house, let me know if I should make a brand new file for just this method alone.

2020-08-19 03:59 UTC, louisraymond commented
Here is the output for `rake test`

```
root@louis:~/louis-fork-media-types/media-types-ruby# rake test
Started with run options --seed 46848

  84/84: [====================================================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.03921s
84 tests, 271 assertions, 0 failures, 0 errors, 0 skips
root@louis:~/louis-fork-media-types/media-types-ruby# 
```

2020-08-19 15:36 UTC, thexa4 commented on lib/media_types/dsl.rb
> +        assert_sane! unless self.media_type_validations.scheme.assertions_executed
Re-executing `validate!` should not result in different results, if we skip running assertions when they've been run once a second run of `validate!` will suddenly succeed.

2020-08-19 23:23 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        assert_sane! unless self.media_type_validations.scheme.assertions_executed
In other words: they may only be skipped if they were valid, but not if they failed

2020-08-20 19:37 UTC, louisraymond commented
@thexa4  made a really good point in discussion today about the design of the test suite, pointing out that it would be better to generate an individual test per fixture to really make the tests as targeted and informative as possible,  
Currently, the information we need is displayed to the user with the tests generating the way I have done. because of this  this suggestion would be an upgrade rather than a fix, So I would like to implement that in another PR as an upgrade, rather than delay.

2020-08-21 00:06 UTC, SleeplessByte commented on test/test_helper.rb
> +  def assert_media_type(media_type)
Yeah this is good. Can you document it in Readme.md how to include? Then this part is good enough to merge.

2020-08-21 00:06 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        assert_sane! unless self.media_type_validations.scheme.assertions_executed
@louisraymond if you resolve this final issue, we can get this merged

2020-08-21 00:06 UTC, SleeplessByte commented
Yah I agree. There's only 2 more small things for you left to do, then we merge it 💯

2020-08-21 04:09 UTC, louisraymond commented
```
12 tests, 58 assertions, 0 failures, 0 errors, 0 skips
root@louis:~/louis-fork-media-types/media-types-ruby# rake test Started with run options --seed 23486

  84/84: [==================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.04517s
84 tests, 271 assertions, 0 failures, 0 errors, 0 skips
root@louis:~/louis-fork-media-types/media-types-ruby# 
```

2020-08-24 13:52 UTC, SleeplessByte approved these changes
See inline, should be answered / fixed.

@thexa4 can you check once more as well?

~Next PR: `assert_sane!` should raise, `assert_media_type` should not.~

2020-08-24 13:52 UTC, SleeplessByte commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
Do I need to require a file?

2020-08-24 13:52 UTC, SleeplessByte commented on README.md
> +  class AnyType
Is it common to define the media type inside the test?

2020-08-24 13:52 UTC, SleeplessByte commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format.rb'
Will this break if I don't have Minitest?

2020-08-24 13:52 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        to_constructable.validate!(output, **opts) if target_scheme.asserted_sane
Is this check necessary? The line above raises if not sane, so this is never reached, right?

2020-08-24 14:08 UTC, thexa4 requested changes

2020-08-24 14:08 UTC, thexa4 commented on test/media_types/dsl/attribute_test.rb
> +          execute_assertions(AttributeType)
Why are you executing the asserts here during loading?

2020-08-24 14:33 UTC, SleeplessByte commented
~Next PR: `assert_sane!` should raise, `assert_media_type` should not.~

I think what we need feature wise is this:

- `assert_sane!` MUST raise if not sane
- There should be actionable, detailed failures in the test suite. This can be achieved in two ways, or both:
  - `assert_media_type` should use minitest failures, report which fixture(s) fails, where it failed, what the input was, what was the validation error: in short a very good error message
  - Dynamically generate the test, where much of the required information can be derived from the _test name_.

So the requirements are:

- `assert_sane!` is not test-related and show raise a custom error. The error message is important, but we can make this _better_ later.
- the test suite should yield failures (NOT errors), and those failures should have enough information to:
  - which fixture failed
  - why did it fail

I think that's what's necessary to facilitate a Gem release

2020-08-24 18:13 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
The MediaType definition should be unique though, therefore the particular case should already be unique and easy to find. Obtaining the file + line number of the call to `assert_pass` or `assert_fail` doesn't seem like a straightforward thing to do. I'm not sure this is required.

Could use `caller_locations` for this: doesn't work very well in the context of byebug
something like this 
```Ruby
caller_locations(0)[14]
"/root/media-types-ruby/lib/media_types/scheme.rb:401:in `assert_pass'"
```
Though I think in normal use, that would be `caller_locations(0).first` . I don't think that we actually need this though

2020-08-24 19:09 UTC, louisraymond commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format.rb'
No, minitest is just what the directory is called, but there are no direct references to the gem. My guess is that when this was named the intention was that this directory would contain methods we provide that would be used in tests, but it's not directly connected, or dependent, on minitest

2020-08-24 19:10 UTC, louisraymond commented on README.md
> +  class AnyType
Within the gem itself, this is how we seem to historically have mocked things, but- If  I remember correctly ( I will double check), in TrailerVote, we defined some of the MediaTypes outside the class.

2020-08-25 13:55 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
No, you only need to have installed the gem and include this module - I just checked this in a fake project

2020-08-25 13:59 UTC, louisraymond commented on README.md
> +  assert_sane!
Might be a stupid question/thought, but the only other use of assert_sane! is in validate! etc. assert_sane is still available for the user to use when developing their own stuff, and I think they might want to use it like this during development of their own stuff. I agree that this shouldn't be in the canonical example for the feature, but perhaps I should explain that there is a use case/ reason to do this? I'm not sure

2020-08-25 14:05 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
> doesn't work very well in the context of byebug something like this

Why doesn't it work very well? `caller_locations` is an array (call stack). You probably need to traverse it.

2020-08-25 14:06 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
> The MediaType definition 

In Ruby, you can have the same class opened up many times. It would be good to know which definition has errored.

2020-08-25 14:10 UTC, SleeplessByte commented on README.md
> +  class AnyType
What I mean is: when using this library, is it expected to define media types inside tests? Because I doubt that to be the case.

2020-08-25 14:10 UTC, thexa4 commented on README.md
> +  assert_sane!
Why would the user want to crash their app intentionally?

2020-08-25 14:12 UTC, SleeplessByte commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
That's cool! Does it work when minitest is not a dependency of said project?

2020-08-25 14:12 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
A validation block will likely contain multiple individual `assert_fail '{}'` statements, you need to know which one fails.

2020-08-25 14:37 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
![image](https://user-images.githubusercontent.com/39345994/91188104-d2b37980-e6e8-11ea-8844-e87e2148bd07.png)

Yes- this project doesn't have minitest as a dependency, but you can still use the method is you include the relevant module

2020-08-25 14:38 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
Lol, the above image is from me commenting out the include bit to check it works as I described

2020-08-25 14:40 UTC, louisraymond commented on README.md
> +  assert_sane!
They might want to know, when writing out the media type and thinking they are finished, that it works, so they might want to use assert_sane! in that context to cause the errors to get raised and to get a message in the terminal if they are wrong. So as a development tool- That is how I would use it

2020-08-25 15:05 UTC, thexa4 commented on README.md
> +  assert_sane!
In that case you'd still want to run it outside the definition of the validator, otherwise you might not run all asserts.

2020-08-25 16:20 UTC, SleeplessByte commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
Sooooo it doesn't work 😄.

It's common to _not_ autoinclude minitest etc. files, but have it documented how to include it. Or to check if Minitest is defined, and if it is,. to autoinclude it.

2020-08-25 18:37 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
Yeah it does

2020-08-25 18:38 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
![image](https://user-images.githubusercontent.com/39345994/91214056-76615180-e70a-11ea-834c-c8530388d2b1.png)

2020-08-25 18:39 UTC, louisraymond commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
if you comment out line 4 in the above, you lose access to the method
- this project doesn't have minitest and it works

2020-08-25 18:59 UTC, thexa4 commented on README.md
> +We provide you with the ability to test Media Types you create in the same manner as `assert_sane!` in a Minitest test suite. To do this you must include the `MediaTypes::Assertions` module from the
Doesn't it give an argument error instead of it working?

2020-08-25 20:21 UTC, louisraymond commented on README.md
> +  assert_sane!
I'll make that change

2020-08-26 02:35 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
```Ruby
 FAIL["test_{:foo=>42} expected to fail validations for MediaTypes::Dsl::AnyTest::AnyType", #<Minitest::Reporters::Suite:0x000055e0fc5023b8 @name="MediaTypes::Dsl::AnyTest">, 0.008344823960214853]
 test_{:foo=>42} expected to fail validations for MediaTypes::Dsl::AnyTest::AnyType#MediaTypes::Dsl::AnyTest (0.01s)
        Fixture: {:foo=>42} expected to fail validation check in MediaTypes::Dsl::AnyTest::AnyType at /root/media-types-ruby/test/media_types/dsl/any_test.rb:39:in `block in <class:AnyType>', but it did not
        /root/media-types-ruby/test/media_types/dsl/any_test.rb:251:in `block (3 levels) in <class:AnyTest>'
```

2020-08-26 02:35 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      @msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class}, but it did not"
works

2020-08-26 04:08 UTC, louisraymond commented
Almost there:
I am struggling with a bug that has come up:

```Ruby
      [AnyType, AnyOfScheme, AnyWithOptions, AnyWithOptionsOrNil, AnyWithScheme, AnyWithForce].each do |type|
        MediaTypes::Assertions.build_fixture_tests AnyType


        # scheme = type.media_type_validations.scheme
        # require 'byebug'
        # # byebug
        # scheme.fixtures.each do |object| 
        #   json, caller = [JSON.parse(object[:fixture], { symbolize_names: true }),object[:caller]]
        #   string = "#{json} expected to #{object[:expect_to_pass] ? "pass" : "fail"} validations for #{type}"
        #   output =  object[:expect_to_pass] ? scheme.process_assert_pass(json,type,caller) : scheme.process_assert_fail(json,type,caller)  
  
        #   define_method "test_#{string}" do
        #     assert output == nil , MediaTypes::MediaTypeValidationError.new(json,type,object[:expect_to_pass],caller).msg
        #   end
        # end

      end
``` When the commented out code is enabled INSTEAD MediaTypes::Assertions.build_fixture_tests AnyType , (the body of which is the exact same code) it creates 1/15th of the tests (tests are being duplicated 15 times)
I can't see where the extra looping is coming from

2020-08-26 04:26 UTC, louisraymond commented
Dealing with a bug
The new tests I'm generating are being duplicated and I can't work out why- going to push up some of the code, 

Aside from this bug
```
assert_sane! is not test-related and show raise a custom error. The error message is important, but we can make this better later.
the test suite should yield failures (NOT errors), and those failures should have enough information to:
which fixture failed
why did it fail
```
This, I think, has been satisfied-( but obviously cannot move forward and merge without addressing the glitch, the number of tests goes up to over 800 when you use the full feature, which, is not what we want (also, one fixture can cause 15 failures if that one fixture fails.) So I have some debugging to do here

2020-08-26 16:19 UTC, louisraymond commented
At the moment I have placed the method responsible for building out all the tests we need in the test helper. It has the logic we want and it works now- but I have a feeling that it's not where it ought to be (because the users of the library need to use it) The question is: Where should it go? It doesn't seem quite right to place it in `MediaTypes::Assertions` , Do you have any thoughts/advice?

2020-08-26 16:27 UTC, louisraymond commented
1.  I think `assert_sane!` already meets the requirements, unless I am confused/missing something
2. These things 

> assert_media_type should use minitest failures, report which fixture(s) fails, where it failed, what the input was, what was the validation error: in short a very good error message
> Dynamically generate the test, where much of the required information can be derived from the test name.

Are satisfied by the test suite now, which produces messages such as:
```Ruby
Started with run options --seed 43133

 FAIL["test_{:foo=>[42]} expected to pass validations for MediaTypes::Dsl::AnyTest::AnyType", #<Minitest::Reporters::Suite:0x0000559e162dad20 @name="MediaTypes::Dsl::AnyTest">, 0.014445680193603039]
 test_{:foo=>[42]} expected to pass validations for MediaTypes::Dsl::AnyTest::AnyType#MediaTypes::Dsl::AnyTest (0.01s)
        Fixture: {:foo=>[42]} expected to pass validation check in MediaTypes::Dsl::AnyTest::AnyType at /root/media-types-ruby/test/media_types/dsl/any_test.rb:25:in `block in <class:AnyType>', but it did not
        /root/media-types-ruby/test/test_helper.rb:42:in `block (2 levels) in build_fixture_tests'

  79/79: [==================================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.03846s
79 tests, 266 assertions, 1 failures, 0 errors, 0 skips
```

Telling you where the fixture is with `ruby/test/media_types/dsl/any_test.rb:25:i` and also guiding you with the auto-generated name.

However, I am unsure about where to place the logic for this to make it a public part of the library so other people can use it- the place where I placed  the previous method doesn't seem appropriate.

The method `assert_media_type` works still, and still provides some useful functionality hypothetically, so I don't see a reason to remove it. I don't think it makes sense to call the method currently generating the tests `assert_media_type` because that name doesn't quite capture what the new method does. What are your thoughts on what to do with `assert_media_type` ?

The rest of today I am going to clean up the ReadMe and other minor issues that got mentioned in the last round of feedback

2020-08-27 13:17 UTC, SleeplessByte commented
> At the moment I have placed the method responsible for building out all the tests we need in the test helper. It has the logic we want and it works now- but I have a feeling that it's not where it ought to be (because the users of the library need to use it) The question is: Where should it go? It doesn't seem quite right to place it in `MediaTypes::Assertions` , Do you have any thoughts/advice?

`MediaTypes::MiniTest`

or just `MiniTest` 

or something like that. Definitely not `test_helper`, and definitely inside `lib`.

2020-08-27 13:29 UTC, SleeplessByte commented
> 1.I think assert_sane! already meets the requirements

I don't think it does. It raises an error, but the message is non-actionable.

> 2. Are satisfied by the test suite now, which produces messages such as:

Has the same issue. The message isn't minitest-like. I expect:

- Two fixtures with the same data will yield two tests, which currently doesn't happen. The second will override the first. Maybe at the fixture index?
- ` test_{:foo=>[42]} expected to pass validations` this isn't much better than "It didn't pass". I'm looking for the actual failure, which should be something along the lines of: "expected `. -> :foo -> :a`, but found Array instead". 
- `at /root/media-types-ruby/test/media_types/dsl/any_test.rb:25:` is this helpful information? I'd rather see where the test was defined, and the fixture was defined.

> However, I am unsure about where to place the logic for this to make it a public part of the library so other people can use it- the place where I placed the previous method doesn't seem appropriate.

The `lib` folder is public API.

> What are your thoughts on what to do with `assert_media_type` 

If it works, you can keep it. 


We're available after the call, should you need us.

2020-08-27 14:39 UTC, louisraymond commented
FAIL["test_{:foo=>[42]} expected to pass validations for MediaTypes::Dsl::AnyTest::AnyType", #<Minitest::Reporters::Suite:0x0000557f45e33590 @name="MediaTypes::Dsl::AnyTest">, 0.016041803173720837]
 test_{:foo=>[42]} expected to pass validations for MediaTypes::Dsl::AnyTest::AnyType#MediaTypes::Dsl::AnyTest (0.02s)
        Fixture: {:foo=>[42]} expected to pass validation check in MediaTypes::Dsl::AnyTest::AnyType at /root/media-types-ruby/test/media_types/dsl/any_test.rb:25:in `block in <class:AnyType>', but it did not - expected to follow [Rules n=0 optional=0 allow_empty=false]
          *: [Scheme::Attribute of Numeric]
        [/Rules]
        /root/media-types-ruby/test/test_helper.rb:42:in `block (2 levels) in build_fixture_tests'

  79/79: [================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.03799s
79 tests, 266 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1)
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)
root@louis:~/media-types-ruby#

2020-08-27 15:25 UTC, louisraymond commented
1. The tests overwrite each other and need to be unique

Solution: Add a counter to make test methods unique if a fixture appears twice

 2. The test factory logic needs to be moved to the lib folder to be provided to users of the library

Solution: Either create a new module in lib that provides access to this, or preferably, look at how to patch MiniTest, Look at how Rails patches minitest and write the factory method there.

3. Remove `assert_media_type` 's  implicit dependency on  `assert_sane!` by refactoring it not to use `execute_assertions`.

Solution:  Refactor assert_media_type & possibly delete or refactor execute assertions

4. Now that `execute_assertions` isn't done in the test suite, do we really need it? 
Solution: Decide/Investigate if we do or don't and refactor accordingly.

5. Assert_fail's error message gives too much information. It isn't needed to provide the scheme.

 Solution: make the error message different for `assert_pass` and `assert_fail` errors in Scheme. and have this reflected in the test suite.

6. Assert_pass's error message is too noisey, it would be better to generate a message about *why* a particular case failed and where the error occured, rather than just the information required to deduce that, which is too much and not user-friendly.

solution: refactor the error message, possibly borrow logic from `validate?` or its related methods.

7) Mock building a test suite in _another gem_  *including a fake test suite* with the gem locally installed, to make sure that the factory methods etc. are publicly available, and work as intended when used elsewhere

2020-08-31 18:36 UTC, SleeplessByte requested changes

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      error
```suggestion
        exception.message + " at #{caller.path + ':' + caller.lineno.to_s}"
      end
```

Doest this not work?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      expectation_met = false
This variable is unnecessary. There is a code-path where raising the error makes sense.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    attr_reader :msg
Remove this (see below).

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @msg = "#{json} was expected to fail validations at #{caller.path + ':' + caller.lineno.to_s}"
`StandardError` takes a single argument called `message`. This extra instance variable is superfluous.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        output =  object[:expect_to_pass] ? process_assert_pass(json, caller) : process_assert_fail(json, caller)
Inconsistent whitespace

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +When using this library to make your own media types, you can use the methods `assert_pass` and `assert_fail`  to run checks that your new Media Type matches your expectations.
```suggestion
When using this library to make your own media types, you can use the methods `assert_pass` and `assert_fail` to define checks that your new Media Type matches your expectations.
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +The first two of these methods take in a fixture (as shown below) & store checks you want to carry out when either `assert_sane!` or `assert_media_type` gets called.
```suggestion
These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` or `assert_media_type` is called. 
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convienient way to check that a MediaType you are building is operating as you intend. If an error gets raise
```suggestion
`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convenient way to check that the MediaType you are building is operating as you intend. It raises with a list of failing fixtures if any of the expectations aren't met. 
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +Alternatively, the first time the `validate!` method gets called to check a Media Type fixture, the collection of checks queued up by `assert_pass` and `assert_fail` for the Media Type in question wi
```suggestion
Alternatively, the first time the `validate!` method is called on a Media Type, the collection of assertions stored (defined by `assert_pass` and `assert_fail`) for that Media Type are executed. If any of the assertions fail, subsequent calls to `validate!` re-run the assertions. 
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +```Ruby
````suggestion
```ruby
````

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +When using this library to make your own media types, you can use the methods `assert_pass` and `assert_fail`  to run checks that your new Media Type matches your expectations.
Is there a reason that you've written Media Type and not media type or `MediaType`?

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +The first two of these methods take in a fixture (as shown below) & store checks you want to carry out when either `assert_sane!` or `assert_media_type` gets called.
There are only two methods mentioned above. For legibility, don't use short-hands, simplify tense and redirections.

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convienient way to check that a MediaType you are building is operating as you intend. If an error gets raise
Spelling mistakes.

`assert_sane!` _never_ returns when it fails. It raises an error.

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +Alternatively, the first time the `validate!` method gets called to check a Media Type fixture, the collection of checks queued up by `assert_pass` and `assert_fail` for the Media Type in question wi
Matches wording before, and adds the case on failure.

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +  assert_sane!
```suggestion

  # Optionally assert that the media type is sane on load. This makes the application crash when this
  # file is evaluated. Alternatives include using a _test_ (see below), calling this manually or
  # relying on the program to halt when the media type is used (and invalid).
  assert_sane!
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +Note that while `assert_pass` and `assert_fail` are methods for use inside the validations block, `assert_sane!` is a method that the `MyMedia` class itself has access to.
```suggestion
**Note**: `assert_pass` and `assert_fail` are methods that can _only_ be used inside the `validations` block; `assert_sane!` is a method that the `MyMedia` class itself has access to, and is part of the public API.
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +In the context of your tests, we provide you with the `assert_media_type` method, which acts as a wrapper for `assert_sane!` and allows you to run the checks you queue up for a particular MediaType w
```suggestion
In the context of your tests, we provide the `assert_media_type` method, which acts as a wrapper for `assert_sane!` and allows you to run the checks you queue up for a particular `MediaType` within your tests.
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +In the context of your tests, we provide you with the `assert_media_type` method, which acts as a wrapper for `assert_sane!` and allows you to run the checks you queue up for a particular MediaType w
Here you used MediaType, instead of Media Type. It should be consistent through-out the document. My guess is that you meant the "custom klazz", and in that case it should be `MediaType`.

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +To do this you must include the `MediaTypes::Assertions` module from the gem, as follows
```suggestion
Include the `MediaTypes::Assertions` module from the gem to use `assert_media_type`:
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +  class MyMedia
```suggestion
class MyMedia
```

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +
````suggestion
```ruby
````

2020-08-31 18:36 UTC, SleeplessByte commented on README.md
> +  def test_MyMedia
```suggestion
  def test_my_media
```

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format.rb'
```suggestion
require 'media_types/minitest/assert_media_type_format'
```

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types.rb
> +require 'media_types/minitest/test_factory.rb'
```suggestion
require 'media_types/minitest/test_factory'
```

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        assert_sane! unless target_scheme.asserted_sane
Methods that answers a question should end with `?`

```suggestion
        assert_sane! unless target_scheme.asserted_sane?
```

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        self.media_type_validations.execute_assertions(self.class)
Here assertions are execute on the validations, but above the saneness is asserted on the `scheme`. Should probably be the same?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/assert_media_type_format.rb
> +    def traceless_assert(test, msg = nil)
What is the purpose of "tracelessness"?

Why is there a counting side-effect? 

What's the reason of not using something already built-in?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +  def self.build_fixture_tests(type)
```suggestion

  def self.build_fixture_tests(klazz)
```

The canonical name for a type isn't `type` but `klazz`.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +    counter = 1
Bookkeeping variables are _almost never_ necessary in ruby.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +    scheme.fixtures.each do |object|
Instead of iteration `each`, use something that iterates both the object and the index, so you can get rid of `counter`

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +      string = "test_fixture-#{counter}:(#{json})_for_#{type}"
`string` is not a descriptive name. Change it to something more descriptive.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +      output = object[:expect_to_pass] ? scheme.process_assert_pass(json, caller) : scheme.process_assert_fail(json, caller)
`output` is not a descriptive name. From the code below it's _maybe_ a string?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +      output = object[:expect_to_pass] ? scheme.process_assert_pass(json, caller) : scheme.process_assert_fail(json, caller)
This seems to _execute_ the assertion?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +        traceless_assert output.nil?, message
This doesn't actually _run_ the assertion, because that's already done on line 12. 

The assertion should run inside the test, not outside of it.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +      message = object[:expect_to_pass] ? output :  MediaTypes::MediaTypeValidationError.new(json, caller).msg
```suggestion
      message = object[:expect_to_pass] ? output : MediaTypes::MediaTypeValidationError.new(json, caller).msg
```

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/minitest/test_factory.rb
> +  def self.build_fixture_tests(type)
This method reads as pretty complex. Probably a way to simplify it or extract commonalities

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      object_to_store = {
This is called "primitive obsession". Consider using a new `class` or if you must a `Struct` / `OpenStruct`.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        json = JSON.parse(object[:fixture], { symbolize_names: true })
Is symbolizing always the correct behaviour? Should that be a setting? Is Oj available? How do we handle this inside the library itself?

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise AssertionError, errors.map { |error| error.msg } unless errors.empty?
We probably want to capture all the errors, not just the messages, and build the message inside `AssertionError`.

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    def execute_assertions(media_type_class)
```suggestion
    def execute_assertions
```

Argument is not used

2020-08-31 18:36 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      errors = []
This is a bookkeeping variable. You probably wanted to use `each_with_object([])`

2020-09-01 04:59 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      errors = []
I'm thinking that `execute_assertions` and `assert_sane!` are both helper functions that would be nice to include, but they are not entirely germaine to the goals of the PR.
`execute_assertions` is also the most problematic addition to the repo, (except the test factory, which needs to be cut down a bit`. 
Are you open to me shelving the helper methods, which sort of evolved from an earlier approach to building this, and putting them in the next release as a minor upgrade? I will try to refactor them and test them and everything, but perhaps it makes more sense to shelve them for this release?

2020-09-01 05:00 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      errors = []
`execute_assertions`  at this point is only used by `assert_sane!` or as a helper function

2020-09-01 05:15 UTC, louisraymond commented on lib/media_types/minitest/assert_media_type_format.rb
> +    def traceless_assert(test, msg = nil)
# traceless_assert enables you to write test factories and so one without providing a backtrace to the code where the method was defined, apart from this, it is identical to a normal assert.
    # this is so that you can create methods such as the ones in ./test_factory.rb which only provide information captured in the error,
    # and avoid providing an unhelpful backtrace to the file where the template test was written.

I was looking for part of minitest that would let you do this, the closest thing I could find was the Backtrace Silencers that rails uses, but they seemed to have to be applied globally, or as a setting-I needed something that would either let me provide my own backtrace data, or removed the default one, but only for the relevant tests. 
Because we already had messages designed with the backtrace info in, and these messages were shared and used by helper methods, I built something to take the second option, and provide the useful info in the error message, and clip out the misleading stack trace (it lead to the test factory instead of the assert_pass/assert_fail call)

2020-09-01 05:16 UTC, louisraymond commented on lib/media_types/minitest/assert_media_type_format.rb
> +    def traceless_assert(test, msg = nil)
`Why is there a counting side-effect?

I think a normal `assert` counts the assertions in this way, since this is replacing a normal minitest `assert` , it also needs to do the counting.

2020-09-01 12:49 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      errors = []
Actually not sure it can be removed as `assert_sane!` is used to check things the first time you run validate, if something is not asserted_sane, so might have been wrong about being able to shelve this part of the feature

2020-09-01 14:47 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      error
I am trying to do one of the refacorings requested

and I cannot see why

   def process_assert_pass(json, caller)
      validate(json)
    rescue StandardError => e
      error = e.message + "\n#{caller.path + ':' + caller.lineno.to_s}"
    end
sometimes returns true, which is not what I want

while

def process_assert_pass(json, caller)
      error = nil
      begin
        validate(json)
      rescue StandardError => e
        error = e.message + "\n#{caller.path + ':' + caller.lineno.to_s}"
      end
      error
    end
Does not

Do either of you see what the error I am making could be?

this is also the case if you remove the error on line 8 of the second example

2020-09-01 14:48 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      error
I went through this process when I first wrote the method, as I also initially thought the suggested way would provide the same result

2020-11-20 17:31 UTC, thexa4 requested changes

2020-11-20 17:31 UTC, thexa4 commented on README.md
> +  # Optionally assert that the media type is sane on load. This makes the application crash when this
We don't actually want people to let the application crash when files are evaluated right?

2020-11-20 17:31 UTC, thexa4 commented on README.md
> +**Note**: `assert_pass` and `assert_fail` are methods that can _only_ be used inside the `validations` block; `assert_sane!` is a method that the `MyMedia` class itself has access to, and is part of
What is the `MyMedia` class? Why does only that class have access to it when the next part says it should be part of the public API?

2020-11-20 17:31 UTC, thexa4 commented on README.md
> +In the context of your tests, we provide the `build_fixture_tests` method,which allows you to run the checks you queue up for a particular `MediaType` within your tests with `assert_pass` and `assert
Why would you want to test fixtures? Wouldn't it be more useful to test the media type you created?

(not really clear why I would use this)

2020-11-20 17:31 UTC, thexa4 commented on lib/media_types/scheme.rb
> +    # Rename to assertion?
This looks like a TODO?

2020-11-20 17:31 UTC, thexa4 commented on lib/media_types/scheme.rb
> +    def execute_assertions
The naming for this method is probably not entirely clear. How are you supposed to use this method?

2020-11-20 17:31 UTC, thexa4 commented on lib/media_types/validations.rb
> +    attr_reader :scheme
Is the comment below related to this line?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types/dsl/attribute_test.rb
> +          'AttributeCollectionType'
Why did you replace the organisations?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  # Supposed to FAIL!!!
Is the definition of this media type supposed to fail?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  # refactor media types to match above
This looks like a TODO

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +    assert NoKeyTypeSpecified.symbol_keys?
Isn't this already covered by the tree matrix test?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +        # Make it assert a specific error class
This looks like a TODO

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  def test_that_MediaTypesTest_TreeTestRoot_NoKeyTypeSpecified_has_the_expected_key_type_preference
This test name is hard to understand.

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +    assert validate_module_inheritance(MediaTypesTest::TreeTestRoot::NoKeyTypeSpecified), expected
This asserts that `expected` has the same value as `validate_module_inheritance(MediaTypesTest::TreeTestRoot::NoKeyTypeSpecified)`

If this fails there is no actionable path to fixing it.

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  def test
What does this function do?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  def validate_module_inheritance(target_module)
You are dynamically generating the expected result, do you have tests proving that this function generates the correct results?

2020-11-20 17:31 UTC, thexa4 commented on test/media_types_test.rb
> +  def demodulize(mod)
What does this function do?

2020-12-03 14:57 UTC, VincentRbbmnd commented on lib/media_types/validations.rb
> +    attr_reader :scheme
Comment below seems related to the `find` method below it.

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/dsl.rb
> +        self.media_type_validations = Validations.new(to_constructable, symbol_keys? ? Symbol : String, &block)
It might be more ergonomic to have `key_type` return `Symbol` or `String` and not have this conditional statement here.

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
What happens if I do:

```ruby
attribute "foo"
attribute :foo
```

Is the behaviour the same as:
```ruby
attribute :foo
attribute "foo"
```

Is the behaviour the same as:
```ruby
attribute :foo
attribute :foo
```

Is the behaviour the same as:
```ruby
attribute "foo"
attribute "foo"
```

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A collection with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
Same question as `attribute`

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +        normalized_key = verify_type_and_normalize_key(key, false)
Instead:

```suggestion
        normalized_key = normalize_key(key)
```

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +        __getobj__[verify_type_and_normalize_key(key)]
Instead:
```suggestion
        __getobj__[normalize_key(verify_key_type(key))]
```

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +        __getobj__.fetch(verify_type_and_normalize_key(key, false), &block)
Same as above

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +        __getobj__.delete(verify_type_and_normalize_key(key))
Same as above

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +      def verify_type_and_normalize_key(key, doVerify = true)
It's very non-rubyesque to define two methods as one method with a flag. Instead, having two methods that _only_ execute their own responsibility is much more idiomatic.

I recommend splitting this in `normalize_key` and `verify_key_type` and be explicit about it.

2020-12-30 17:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules.rb
> +        return normalized_key
```suggestion
        normalized_key
```

In ruby, you don't need to `explicitly` return at the end of a method.

2020-12-30 19:20 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
Since all keys are now stored normalized as Symbol type, it was no longer possible to differentiate between each of those cases. And we are otherwise indifferent to the key type used in the validation rules itself I decided that a more general approach was necessary.
So for each of your cases it reports the same error now. That the key is a duplicate because its string representation equals another's.

2020-12-30 19:24 UTC, Dortund commented on lib/media_types/scheme/rules.rb
> +      def verify_type_and_normalize_key(key, doVerify = true)
That makes sense. Will do.

2020-12-30 19:26 UTC, Dortund commented on lib/media_types/scheme/rules.rb
> +        return normalized_key
Old habits and such. Will update when splitting the method.

2020-12-30 20:06 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
Are you _certain_ that each case reports as the same error?

2020-12-31 14:08 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
I tested it. Each case gives the DuplicateKeyError. Although admittedly the if statement can be simplified if we're not trying to distinguish between every case

2020-12-31 17:24 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if (key.is_a?(String) && rules.has_key?(String(k
I'm mostly concerned with the error message no longer matching what is going wrong. Having two distinct error cases instead of this "combined one" make more sense to make, and the combined one is "difficult enough" that I had to ask if it's correct.

2021-01-05 14:32 UTC, thexa4 requested changes

2021-01-05 14:32 UTC, thexa4 commented on lib/media_types/minitest/test_factory.rb
> +    fixtures = mediatype.media_type_validations.scheme.fixtures
Does this work with fixtures in subschemes?

2021-01-05 14:32 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      @message = "#{json} was expected to fail validations"
Why is it a problem that some piece of json was marked to fail?

2021-01-05 14:32 UTC, thexa4 commented on lib/media_types/scheme/rules.rb
> +      def normalize_key(key)
Shouldn't we do the normalization at an earlier point?

2021-01-05 14:32 UTC, thexa4 commented on test/media_types/key_type_expectations_test.rb
> +    def test_that_MediaTypesTest_TreeTestRoot_NoKeyTypeSpecified_StringKeyTypeSpecified_NoKeyTypeSpecified_has_the_expected_key_type_preference
You probably want to use a name that describes what property you are asserting instead of how you set up the test.

2021-01-05 14:32 UTC, thexa4 commented on test/media_types/key_type_expectations_test.rb
> +      assert TreeTestRoot::StringKeyTypeSpecified::StringKeyTypeSpecified::StringKeyTypeSpecified::TestMediaType.string_keys?
Doesn't this result in a ton of useless failures if you make a programming mistake?

2021-01-05 14:32 UTC, thexa4 commented on test/media_types/key_type_expectations_test.rb
> +    class NoKeyTypeSpecified
Aren't these classes the same as the module tree below?

2021-01-05 14:54 UTC, SleeplessByte commented on test/media_types_test.rb
> +  def demodulize(mod)
My guess is [this](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-demodulize)

> Removes the module part from the expression in the string.

```ruby
demodulize('ActiveSupport::Inflector::Inflections') # => "Inflections"
demodulize('Inflections')                           # => "Inflections"
demodulize('::Inflections')                         # => "Inflections"
demodulize('')                                      # => ""
```

```ruby
# File activesupport/lib/active_support/inflector/methods.rb, line 221
def demodulize(path)
  path = path.to_s
  if i = path.rindex("::")
    path[(i + 2)..-1]
  else
    path
  end
end
```

2021-01-05 15:40 UTC, thexa4 commented on lib/media_types.rb
> +    @key_expectations ||= {}
I'd expect an error to be raised here if changing the key expectation would change a key type in a validator that has been used so far.

2021-01-06 10:53 UTC, louisraymond commented on README.md
> +`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convenient way to check that the MediaType you are building is operating as you intend. It raises with a list
I think we don't really use assert_sane! as something you keep in your mediatypes, but it's important in the mechanism for the new features. I wanted to keep it exposed to end users as a debugging tool, so they can slot it in as described if they want. but it can even be hidden from them.

2021-01-06 10:57 UTC, louisraymond commented on README.md
> +  assert_sane!
The way I was using this was when I was building MediaTypes and wanted to check that the mediatype I had just written a definition for worked, I used assert_sane! in this way to run the asserts while I was coding. I think you have to put it inside the class because it is an instance method (it's primary use is in validations)

2021-01-06 10:59 UTC, louisraymond commented on README.md
> +These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` is called.
I fused this with the previous paragraph (not pushed yet)  but this is what It could say, if this works


When using this library to make your own media types, you can use the methods `assert_pass` and `assert_fail` to define checks that your new Media Type matches your expectations. These methods take a json string (as shown below) and store assertions to be carried out when  `assert_sane!` is called.

2021-01-06 12:31 UTC, thexa4 commented on README.md
> +  assert_sane!
Wouldn't `MyValidator.assert_sane!` work as well? Seems like it would be harder to call the function when the validator is not yet fully set up.

2021-01-06 12:31 UTC, thexa4 commented on README.md
> +`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convenient way to check that the MediaType you are building is operating as you intend. It raises with a list
It seems pretty essential to keep it, otherwise you can't do preflight checks.

2021-01-06 12:34 UTC, thexa4 commented on README.md
> +These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` is called.
That seems more readable, do we explain elsewhere why you want to use this?

2021-01-06 14:51 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
I think you mean **after** defining a validation? The reason is we need the information to set up the rules. Just like you're required to set a name before defining validations.

2021-01-06 14:54 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise e.class, 'Uninitialized constructable, have you called `use_name(name)` before the validations?'
Not much. The problem is that use_name was not called before defining the validations, so only telling them that should be more clear I suppose

2021-01-06 15:08 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise KeyTypeError, "Unexpected key type #{key.class.name}, please use either a symbol or string." unless key.is_a?(String) || key.is_a?(Symbol)
The same one as the one in attribute(...), prevent a user from entering something in the rules which is neither a symbol or string

2021-01-06 15:14 UTC, thexa4 commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
Right, after defining a validation. Due to variable load order we don't know wether all module types have been set so defining a validation cannot depend on knowing which type it should be. Otherwise you'll get inconsistent results when you don't define a key type override.

2021-01-06 15:15 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      raise KeyTypeError, "Unexpected key type #{key.class.name}, please use either a symbol or string." unless key.is_a?(String) || key.is_a?(Symbol)
Ok, what problem are we avoiding for the user by preventing them from entering a non-symbol or string in either `attribute` or `collection`?

2021-01-06 15:16 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if rules.has_key?(String(key).to_sym)
Somewhat, but because the rules are stored normalized as symbol keys, we don't know what type the original key was, so we cannot distinguish between each of the four cases. Only the two cases regarding which type the current key has, which offers no additional insight about what exactly a user has to change.

2021-01-06 15:18 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if rules.has_key?(String(key).to_sym)
Why do we throw away that information if we need it here?

2021-01-06 15:26 UTC, Dortund commented on lib/media_types/scheme/rules.rb
> +      def normalize_key(key)
Regarding storing the keys? The only earlier part I can think of is before calling Rules.add, which means the assumption that everything is stored as a symbol type can no longer be guarenteed..

2021-01-06 15:32 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Key expectation already set' unless no_expectation_set?
I don't think so. But allowing it would not increase functionality, readability or add anything of value either. So the question is : Is it okay to enforce legible validations?

2021-01-06 16:03 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
That throws a spanner in the works..

2021-01-08 14:05 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise KeyTypeError, "Unexpected key type #{key.class.name}, please use either a symbol or string." unless key.is_a?(String) || key.is_a?(Symbol)
Preventing them from creating a validator which will never accept anything, because we can't handle Integer type key inputs.

Mostly I just saw that we checked it for keys in attribute, but not keys in collection, so I thought I was fixing a bug by adding it to collection and link. Is that not the case?

2021-01-08 14:07 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if rules.has_key?(String(key).to_sym)
Because I thought we wanted to store keys normalized as symbols and did not think we needed also keep track of what the original key type was in the rules.

2021-01-08 14:13 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      raise KeyTypeError, "Unexpected key type #{key.class.name}, please use either a symbol or string." unless key.is_a?(String) || key.is_a?(Symbol)
I don't know why we check for it in attribute so I'm not sure if it should be here. What breaks when you use integers as keys?

2021-01-08 14:15 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with the same string representation as the string '#{key}' already exists. Please remove one of the two." if rules.has_key?(String(key).to_sym)
Ok, so what are our next steps?

2021-01-08 16:00 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise KeyTypeError, "Unexpected key type #{key.class.name}, please use either a symbol or string." unless key.is_a?(String) || key.is_a?(Symbol)
Answer after discussion: Although there is something to be said to allow key types other then string and symbol, we're building a library that works primarily with JSON, which only has string type keys. So limiting the validation rule key type to either string or symbol makes sense.

2021-01-10 19:20 UTC, louisraymond commented on README.md
> +These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` is called.
Do you mean why we want to use assert_pass/ assert_fail? or why we use assert_sane?

Assert_sane is explained by the mechanism used here. I don't think we detail why `assert_pass` and `assert_fail` are present in the library.  I suppose the reason is we are providing a way to prevent users from writing mediaType definitions with consequences they do not really want. I kind of thing the code expresses this purpose by itself? Do you think that a prose explanationation is going to help? I am worried that over-explaining rather than letting the code examples show what you _can do_ is going to muddy the waters? What do you think

2021-01-10 22:47 UTC, thexa4 commented on README.md
> +These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` is called.
My concern is that developers that want to use our library likely aren't very interested in how the mechanism works, they are more likely to look for information on how using this feature might benefit them.

2021-01-11 01:44 UTC, louisraymond commented on README.md
> +`assert_sane!` can be used as a debugging/development tool (as shown below), giving you a convenient way to check that the MediaType you are building is operating as you intend. It raises with a list
Yes, I think I should actually remove the statement about it being used as a debugging tool, that might be too specific to me and my experience, and instead write that it's for testing mediatypes before you use them.

2021-01-11 01:52 UTC, louisraymond commented on README.md
> +  assert_sane!
That's true, but I don't know when a user would want to call assert_sane! outside of the media_type definition, all of our use cases are in the mechanisms for running the checks.

I can see where you are coming from and will change to make that shown, but this isn't what we actually were writing when building this feature. you suggest after the MT definition is closed, and probably makes more sense semantically. 

Also maybe they would like to place the assert_sane! methods all in one place (perhaps a method that gets called in their own workflow) so writing it like you suggest actually makes more sense

2021-01-11 01:54 UTC, SleeplessByte commented on README.md
> +These methods take a fixture (as shown below) and store assertions to be carried out when either `assert_sane!` is called.
It might be okay to document this somewhere for people to read, but the code could be a good place for that. I agree that as a consumer I'd not be interested that much in the inner workings.

2021-01-11 02:30 UTC, louisraymond commented on README.md
> +Alternatively, the first time the `validate!` method is called on a Media Type, the collection of assertions stored (defined by `assert_pass` and `assert_fail`) for that Media Type are executed. If a
No, I removed that now

2021-01-11 02:31 UTC, louisraymond commented on README.md
> +**Note**: `assert_pass` and `assert_fail` are methods that can _only_ be used inside the `validations` block; while `assert_sane!` is part of the public MediaTypes API.
Yes, I think what we are trying to get across here is that assert_pass and assert_fail only really make sense when used inside a MT definition.

2021-01-11 03:10 UTC, louisraymond commented on README.md
> +**Note**: `assert_pass` and `assert_fail` are methods that can _only_ be used inside the `validations` block; while `assert_sane!` is part of the public MediaTypes API.
I just removed this note after thinking about it for a while, because it is rendered moot by the change instigated by the discussion about where to call `assert_sane!` above

2021-01-11 03:13 UTC, louisraymond commented on README.md
> +class MyMedia
Yeah I think it's muddying the waters too. Removed

2021-01-11 03:14 UTC, louisraymond commented on README.md
> +Users are provided with the ability to specify the expected type of keys in the media type, by default symbol keys are expected.
I am not confident about why anymore. just that it caused bugs when we didn't set a preference/rule-set ourseleves. I think we should explain this, not sure what a good way to get this across would be

2021-01-11 03:21 UTC, louisraymond commented on README.md
> +  expect_string_keys
Fixed

2021-01-11 14:45 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    raise format('%<mod>s already has a key expectation set', mod: mod.name) unless @key_expectations[mod.name].nil?
Making the user able to set the key expectation multiple times opens them up to setting a key type expectation in different files where the module is being opened up.
This would lead to the last file loaded setting the expected key type, possibly leading to confusion.
Since a module can only expect one key type, it makes sense to define that once and not rely on files loading and overwriting key expectation for the same module.

2021-01-11 14:47 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    expect_symbol
Not having explicitly set an expected type makes for the default being used, which is handled elsewhere. We could also implement that here.

2021-01-11 14:57 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      class UninitializedConstructable < RuntimeError; end
AFAIK the other error definitions are specific to the `Scheme` class, we can use a similar approach for `Dsl` if you want.

2021-01-11 15:10 UTC, VincentRbbmnd commented on test/media_types/key_type_expectations_test.rb
> +      assert TreeTestRoot::StringKeyTypeSpecified::StringKeyTypeSpecified::StringKeyTypeSpecified::TestMediaType.string_keys?
What do you mean by 'this'? What 'useless failures' and what kind of 'programming mistake'?

2021-01-11 15:19 UTC, thexa4 commented on test/media_types/key_type_expectations_test.rb
> +      assert TreeTestRoot::StringKeyTypeSpecified::StringKeyTypeSpecified::StringKeyTypeSpecified::TestMediaType.string_keys?
If you mess up the behavior of use_string_keys for example, you would get a lot of errors for tests that test what happens if you don't set an expectation.

2021-01-11 15:37 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +        raise e.class, 'Uninitialized constructable, have you called `use_name(name)` before the validations?'
Updated error message, only asking if the user has called use_name before the validations.

2021-01-11 16:35 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      def symbol_keys?
Moved the body of `expecting_symbol_keys?` to `symbol_keys?`

2021-01-11 16:42 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      def no_expectation_set?
Was originally done like this because `no_expectation_set?` reads more nicely than `symbol_keys.nil?`

2021-01-11 16:59 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    @key_expectations ||= {}
Added bookkeeping of modules for which the expectation has successfully been used, raises an error here if this is the case.

2021-01-11 17:46 UTC, VincentRbbmnd commented on test/media_types/key_type_expectations_test.rb
> +    class NoKeyTypeSpecified
Yes, has been resolved

2021-01-15 10:43 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
I think the essence of lines 191 and 192 can be captured by a single statement
```ruby
raise DuplicateKeyError, format('A %<type>s attribute with key %<key>s has already been defined. Please remove one of the two.',type: key.class, key: key) if key.class == rules.has_key?(key)
```

2021-01-15 10:43 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A string keyed attribute with the same string representation as the symbol :#{key} already exists. Please remove one of the two." if key.is_a?(Symbol) && rules.has_key
Same thing for lines 193 and 194

2021-01-15 10:43 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A collection with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
Same as in the attribute function, however this seems to be the exact same code so maybe we can extract this?

2021-01-15 10:43 UTC, VincentRbbmnd commented on lib/media_types/scheme/links.rb
> +        raise DuplicateKeyError, "A link with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && links.has_key?(key) == Symbol)
Same as for attribute and collection

2021-01-15 10:43 UTC, VincentRbbmnd commented on lib/media_types/scheme/rules.rb
> +        if __getobj__.key?(normalized_key)
To me it feels like this line should be what is returned by the function `has_key?`, since function names ending in a question mark indicate that function is going to return a `boolean`. Currently instead of `true` a truthy value is returned in the form of `String` or `Symbol`, a side effect used for type checking. So this function does more than its name tells you, therefore I think we should have a separate function for checking the key type. Maybe something like:
```ruby
def has_key?(key)
  __getobj__.key?(normalize_key(key))
end

def key_type(key)
  raise format('Key %<key>s does not exist', key: key) unless has_key?(key)

  original_key_type[normalize_key(key)]
end
```

2021-01-15 11:56 UTC, VincentRbbmnd commented on README.md
> +U
U?

2021-01-15 13:53 UTC, VincentRbbmnd commented on README.md
> +U
Fixed

2021-01-19 12:41 UTC, louisraymond commented on test/media_types_test.rb
> +  def demodulize(mod)
Yes, is this resolved? @thexa4

2021-01-20 13:12 UTC, VincentRbbmnd commented on Gemfile.lock
> +    minitest (5.14.1)
I think we should revert these changes as this is not the purpose of this PR

2021-01-20 13:21 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    @key_expectations ||= {}
Resolved

2021-01-20 13:21 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      def symbol_keys?
Resolved

2021-01-20 14:22 UTC, VincentRbbmnd commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
One of the tests this function gets used in is in `scheme_test.rb#139`, I'm not sure if we can replicate that behaviour with the new system.

2021-01-21 14:16 UTC, Dortund commented on lib/media_types/scheme/rules.rb
> +      def normalize_key(key)
The code changed since your remark. Is this still something that needs work? Because I can't think of any place earlier to normalize the data and it being practical/usefull..

2021-01-21 14:19 UTC, Dortund commented on lib/media_types/scheme/rules.rb
> +        if __getobj__.key?(normalized_key)
I've updated this per your recommendation. So issue resolve I assume

2021-01-21 14:22 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
True, but doing so will decrease the clarity of the error message, which was something preferred over having less lines. So can this be considered resolved?

2021-01-21 14:23 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A string keyed attribute with the same string representation as the symbol :#{key} already exists. Please remove one of the two." if key.is_a?(Symbol) && rules.has_key
same as for the other DuplicateKeyError comment

2021-01-21 14:28 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A collection with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
The code could be moved to the 'add' function of Rules, but then we can no longer make the distinction between the different rule types (attribute, collection, link) and the error message becomes a bit more vague. Not sure if that is desirable.. @thexa4 probably has an opinion on this.

2021-01-21 14:29 UTC, Dortund commented on lib/media_types/scheme/links.rb
> +        raise DuplicateKeyError, "A link with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && links.has_key?(key) == Symbol)
same as for the other DuplicateKeyError comment

2021-01-21 14:36 UTC, Dortund commented on lib/media_types.rb
> +    raise format('%<mod>s already has a key expectation set', mod: mod.name) unless @key_expectations[mod.name].nil?
If loading files in a different order results in a different media type validation, then that seems like a big problem to me. I see this limiting like a good solution.

2021-01-21 14:42 UTC, Dortund commented on lib/media_types/dsl.rb
> +      class UninitializedConstructable < RuntimeError; end
Probably nice to keep coding style consistent throughout the project.

2021-01-21 14:48 UTC, Dortund commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
What is the new system? I'm afraid I can't help on this one Vincent.

2021-01-21 14:54 UTC, Dortund commented on lib/media_types/scheme.rb
> +      MediaTypeValidationError.new(json, caller) unless expectation_met
It seems like the intended behavior. The goal is for process_fixture_data to accumulate an array with any errors encountered while processing the fixtures.

2021-01-21 15:00 UTC, Dortund commented on lib/media_types/scheme.rb
> +      @message = "#{json} was expected to fail validations"
I can't tell the intended behaviour of this.. the original code seems to be:

@msg = "Fixture: #{json} expected to #{expectation ? "pass" : "fail"} validation check in #{media_type_class} at #{caller}, but it did not - expected to follow #{rules.inspect}"

So it seems that the only case left where this is used is when it 'fails'. But all changes to this line are made by 'root' according to git blame so I don't know who's been working on it.

2021-01-21 15:12 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    raise format('%<mod>s already has a key expectation set', mod: mod.name) unless @key_expectations[mod.name].nil?
Resolved

2021-01-21 15:35 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
But that also means we're no longer required to set the expected key type before validations, so we should remove these checks.

2021-01-21 17:00 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      MediaTypeValidationError.new(json, caller) unless expectation_met
Yes, aggregating errors is being done as to provide an overview of errors occurred while processing.

2021-01-21 17:00 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      MediaTypeValidationError.new(json, caller) unless expectation_met
Resolved

2021-01-21 17:00 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "An attribute with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
Resolved

2021-01-21 17:00 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A string keyed attribute with the same string representation as the symbol :#{key} already exists. Please remove one of the two." if key.is_a?(Symbol) && rules.has_key
Resolved

2021-01-21 17:01 UTC, VincentRbbmnd commented on lib/media_types/scheme/links.rb
> +        raise DuplicateKeyError, "A link with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && links.has_key?(key) == Symbol)
Resolved

2021-01-21 17:09 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      class UninitializedConstructable < RuntimeError; end
Extracted custom error classes to a new file.

2021-01-21 17:09 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +      class UninitializedConstructable < RuntimeError; end
Resolved

2021-01-21 17:22 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    expect_symbol
It now returns the default if nothing is set explicitly

2021-01-21 17:22 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    expect_symbol
Resolved

2021-01-22 11:13 UTC, louisraymond commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
I think this exact behaviour is not covered by our new code, we should keep it

2021-01-22 11:18 UTC, louisraymond commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
Looks like we do still need this

2021-01-22 11:20 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      @message = "#{json} was expected to fail validations"
Would `fixture` be clearer than `json`?

2021-01-22 11:21 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      @message = "#{json} was expected to fail validations"
Me I was root

2021-01-22 15:27 UTC, louisraymond commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
remove 141 and 148 and related test

2021-01-22 15:29 UTC, louisraymond commented on lib/media_types/scheme.rb
> +      raise DuplicateKeyError, "A collection with key :#{key} has already been defined. Please remove one of the two." if (key.is_a?(Symbol) && rules.has_key?(key) == Symbol)
@Dortund's test feature is related, we are going to pair and work on this

2021-01-22 15:38 UTC, louisraymond commented on lib/media_types/scheme/rules.rb
> +      def normalize_key(key)
R3soLV3d !11oneoneone11112211

2021-01-22 15:54 UTC, louisraymond commented on test/media_types/key_type_expectations_test.rb
> +    def test_that_MediaTypesTest_TreeTestRoot_NoKeyTypeSpecified_StringKeyTypeSpecified_NoKeyTypeSpecified_has_the_expected_key_type_preference
1.  rename to something like "Tests inheritance of key type preference"
2. make it one big test (maybe)

2021-01-22 15:55 UTC, louisraymond commented on test/media_types/key_type_expectations_test.rb
> +      assert TreeTestRoot::StringKeyTypeSpecified::StringKeyTypeSpecified::StringKeyTypeSpecified::TestMediaType.string_keys?
will be resolved by batching the asserts into a single test

2021-01-22 15:58 UTC, louisraymond commented on test/media_types_test.rb
> +  class NoKeyTypeSpecified
Not duplicated right now, resolved

2021-01-24 17:50 UTC, louisraymond commented on lib/media_types/dsl.rb
> +        raise KeyTypeExpectationError, 'Set key expectation before defining validations' unless media_type_validations.nil?
resolved

2021-01-24 18:16 UTC, louisraymond commented on test/media_types/key_type_expectations_test.rb
> +      assert TreeTestRoot::StringKeyTypeSpecified::StringKeyTypeSpecified::StringKeyTypeSpecified::TestMediaType.string_keys?
This is resolved, although I think that the tests will be modified tomorrow

2021-01-27 17:40 UTC, thexa4 requested changes

2021-01-27 17:40 UTC, thexa4 commented on README.md
> +1. We provide you with two methods (`assert_pass` and `assert fail`), which enable you to specify JSON fixtures you expect to be complient/non-complient
Shouldn't this be `compliant`?

2021-01-27 17:40 UTC, thexa4 commented on README.md
> +2. We provide methods to turn those fixtures into tests with the `test_specification` method.
Might be good to add a link here

2021-01-27 17:40 UTC, thexa4 commented on README.md
> +In the context of your tests, we provide the `test_specification` method,which allows you to run the checks you queue up for a particular `MediaType` within your tests with `assert_pass` and `assert_
Missing space after comma

2021-01-27 17:40 UTC, thexa4 commented on README.md
> +### Validation Checks
I think headers are supposed to be preceeded by a newline but you might have to check the spec.

2021-01-27 17:40 UTC, thexa4 commented on README.md
> +class MyMedia
This seems like it's the same example as above, why do we need to repeat it?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types.rb
> +    raise format('%<mod>s already has a key expectation set', mod: mod.name) unless @key_expectations[mod.name].nil?
This seems to raise a string, is there a reason we don't use an error class here?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types.rb
> +    @key_expectations_used[current_module] = true if current_module
This doesn't seem to mark parent modules as used, does this also work if you change the default on a parent module?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/dsl.rb
> +        raise e.class, 'Have you called `use_name(name)` before the validations?'
This doesn't seem to describe the problem, only a possible solution.

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/dsl.rb
> +        raise e.class, 'Have you called `use_name(name)` before the validations?'
Why are we reraising an error with a different message instead of emitting a new error or modifying the parent error class?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/dsl/errors.rb
> +          'Constructable has not been initialized'
How would a user fix this?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/dsl.rb
> +        assert_sane! unless target_scheme.asserted_sane?
Shouldn't `assert_sane!` contain this check?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
Do we need this with the new implementation?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/minitest/test_factory.rb
> +      define_method "test_fixtures_for_#{mediatype.to_constructable}" do
Does this mean that we now only have one testcase per mediatype? Why did we switch away from one test per fixture?

2021-01-27 17:40 UTC, thexa4 commented on test/test_helper.rb
> +    include MediaTypes::Assertions
Shouldn't this happen automatically if you include our lib?

2021-01-27 17:40 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      @failed_fixtures = []
How are you handling `assert_fail` and `assert_pass` calls in attribute blocks?

```ruby
attribute :foo do
  assert_fail '{}'
end
```

2021-01-28 11:57 UTC, VincentRbbmnd commented on README.md
> +1. We provide you with two methods (`assert_pass` and `assert fail`), which enable you to specify JSON fixtures you expect to be complient/non-complient
Yes, fixed

2021-01-28 11:58 UTC, VincentRbbmnd commented on README.md
> +2. We provide methods to turn those fixtures into tests with the `test_specification` method.
@thexa4 To be specific, a link to the relevant section in this Readme?

2021-01-28 11:58 UTC, VincentRbbmnd commented on README.md
> +In the context of your tests, we provide the `test_specification` method,which allows you to run the checks you queue up for a particular `MediaType` within your tests with `assert_pass` and `assert_
Good catch, fixed

2021-01-28 11:59 UTC, VincentRbbmnd commented on README.md
> +### Validation Checks
Yes they do, fixed

2021-01-28 12:00 UTC, thexa4 commented on README.md
> +2. We provide methods to turn those fixtures into tests with the `test_specification` method.
yes

2021-01-28 12:02 UTC, VincentRbbmnd commented on README.md
> +class MyMedia
Agreed this is too much, reduced the example.

2021-01-28 20:44 UTC, VincentRbbmnd commented on lib/media_types/minitest/assert_media_type_format.rb
>      def assert_media_type_format(media_type, output, **opts)
We think we do, as stated in the resolved conversation on this same line we don't think we can replicate the behaviour of this code with the new implementation.

2021-01-28 20:57 UTC, VincentRbbmnd commented on lib/media_types/minitest/test_factory.rb
> +      define_method "test_fixtures_for_#{mediatype.to_constructable}" do
The previous situation created a separate test for each fixture with a sequential name (`test_fixture0`, `test_fixture1`, etc) and had code similar to that of `assert_sane!` but was not exactly the same because of the need to report the failures in the test nicely. However, the code effectively did the same so we saw fit to consolidate and have cleaner/dry code at the same time.

This enabled us to leverage the functionality of the `assert_sane!` method in the test, which itself validates all fixtures for the MediaType. `assert_sane!` does not crash on the first failed validation, but instead reports back the fixtures that failed including on which line they are defined if any validation fails occur.

2021-01-28 21:02 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    raise format('%<mod>s already has a key expectation set', mod: mod.name) unless @key_expectations[mod.name].nil?
No particular reason, created two new error classes for these cases. Resolved.

2021-01-28 22:42 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    @key_expectations_used[current_module] = true if current_module
Good catch! Fixed by marking every module checked as `key_expectation_used`, since using the default and falling back on the parent also counts :)

2021-01-28 22:46 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +        assert_sane! unless target_scheme.asserted_sane?
Yeah makes sense, moved the check to `assert_sane!`. Resolved

2021-01-28 23:19 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +        raise e.class, 'Have you called `use_name(name)` before the validations?'
Added more information to the message of the original error class

2021-01-28 23:19 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +        raise e.class, 'Have you called `use_name(name)` before the validations?'
Resolved

2021-01-28 23:20 UTC, VincentRbbmnd commented on lib/media_types/dsl/errors.rb
> +          'Constructable has not been initialized'
Has been made clear in the message. Resolved.

2021-01-28 23:26 UTC, VincentRbbmnd commented on test/test_helper.rb
> +    include MediaTypes::Assertions
I think it does

2021-02-10 15:21 UTC, thexa4 requested changes

2021-02-10 15:21 UTC, thexa4 commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format'
Why are we adding this to our public API?

2021-02-10 15:21 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      raise ConflictingTypeDefinitionError, 'You cannot apply a block to a typed attribute, either remove the type or the block' if block_given? && !type.nil?
Do we no longer need to check the keytype?

2021-02-10 15:21 UTC, thexa4 commented on lib/media_types/scheme.rb
> +      position =  caller_locations[0].to_s.match?(/.*`block \(\d+ levels\) in <class:\w+>'/) ? 0 : 1
Why do we need to use regex matching on the callers? Does this work n levels deep?

2021-02-10 15:21 UTC, thexa4 commented on test/intermediate_fixture_assert_test.rb
> +end
Do we have a test that tests what testing two media types with the same name does?

2021-02-10 20:48 UTC, louisraymond commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format'
To give the user access to these methods. Maybe they could be bundled into one file rather than two, I don't understand why this is problematic? Perhaps I don't understand the probelm

2021-02-10 23:08 UTC, thexa4 commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format'
It seems weird to change the (old) internal way of checking from private to public in the change where we make an improved version available.

If we are sure we want / need to expose this, have we written something in the readme on how to use it?

2021-02-11 14:17 UTC, Dortund commented on lib/media_types/scheme.rb
> +      raise ConflictingTypeDefinitionError, 'You cannot apply a block to a typed attribute, either remove the type or the block' if block_given? && !type.nil?
It got moved to validate_input method in rules.rb, since this line was duplicated at a couple of points along with some of the other checks. Now its handled at a single point.

2021-02-11 15:52 UTC, VincentRbbmnd commented on lib/media_types.rb
> +require 'media_types/minitest/assert_media_type_format'
We did not need to expose the files in the `media_types/minitest` folder and I removed those `require` statements.
These custom assertions are already imported by `test_helper.rb.

2021-02-11 18:49 UTC, thexa4 commented on README.md
> +  MyMedia.assert_sane!
Why do we need both `assert_sane!` and `assert_mediatype_specification`?

2021-02-11 18:49 UTC, thexa4 commented on README.md
> +  assert_sane!
Why do we need this line in the example?

2021-02-11 18:49 UTC, thexa4 commented on README.md
> +
Maybe it would be useful to show that it fails to validate if you validate json parsed with the parser set to strings?

2021-02-12 11:31 UTC, VincentRbbmnd commented on README.md
> +  MyMedia.assert_sane!
`assert_mediatype_specification` is used for testing purposes, it wraps `assert_sane!` and handles the possible outcomes to make the test pass or fail accordingly.

2021-02-12 11:45 UTC, VincentRbbmnd commented on README.md
> +  assert_sane!
We don't :) Removing

2021-02-12 13:32 UTC, SleeplessByte commented
(closing and reopening to try to make the build run)

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      reduced_stack = caller_locations.filter { |location| !location.path.include?(__dir__) }
Should probably be its own function with a comment explaining what is happening / why

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +          failed_fixtures << e.message
These are not failed fixtures. These are "messages of failed fixtures".

Returning errors is ok behaviour, you might want to return an array of errors instead.

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      failed_fixtures = []
This is a bookkeeping variable. I rather see .map { }.compact or something similar

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +          failed_fixtures += e.fixture_errors
Is this an array of errors?

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    def run_fixture_validations(expect_symbol_keys, backtrace = [])
This method and the other 3 validate methods all have primitive envy.

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      json = JSON.parse(fixture_data.fixture, { symbolize_names: expect_symbol_keys })
`require 'json'` should be at top. Yes, JSON is loaded, but that's a side-effect of a different require.

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +        unless fixture_data.expect_to_pass
```suggestion
        unless fixture_data.expect_to_pass?
```

(Also update the `FixtureData` class)

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +          message = (fixture_data.caller.path + ':' + fixture_data.caller.lineno.to_s + ' -> No error encounterd whilst expecting to').to_s
I rather have some error class generate this. It seems weird that it lives here and on line 484.

2021-02-12 14:20 UTC, SleeplessByte commented on lib/media_types/scheme/links.rb
> +              failed_fixtures += e.fixture_errors
Same as above.

2021-02-12 14:20 UTC, SleeplessByte commented on test/media_types/key_type_expectations_test.rb
> +    #                    ---------->NoKeyTypeSpecified
This diagram looks incorrect

2021-02-12 14:20 UTC, SleeplessByte commented on test/test_helper.rb
> +    include MediaTypes::Assertions
If it does, then the readme is incorrect.

2021-02-15 11:34 UTC, louisraymond commented on README.md
> +
I don't think we have a test suite thing for when MiniTest is not used, I am not sure if this is a problem - I guess it's annoying, but they are also free to adapt _assert_sane!_ (or whatever it ends up being called upon release) and make their own wrapper if they want to use Rspec or something. Can expanding the test suite capabilities be in another PR? It sounds like the kind of task that wouldn't get neglected/not included in a future upgrade

2021-02-15 11:48 UTC, SleeplessByte commented on README.md
> +
We don't need to support other test suites, but we do need to explain how other people might want to support it.

2021-02-15 17:16 UTC, VincentRbbmnd commented on lib/media_types.rb
> +    while modules.any? && expect_symbol.nil?
Removed the redundant assignment of `modules` by removing this line:
`modules = current_module.split('::')`

2021-02-15 17:50 UTC, louisraymond commented on README.md
> +
I am not sure what you are trying to ask about

2021-02-15 17:53 UTC, VincentRbbmnd commented on lib/media_types/scheme.rb
> +      json = JSON.parse(fixture_data.fixture, { symbolize_names: expect_symbol_keys })
I believe `require 'json'` is at the top of the file, line 20 at the time of writing

2021-02-15 17:57 UTC, Dortund commented on lib/media_types/scheme.rb
> +      failed_fixtures = []
Updated

2021-02-15 17:57 UTC, Dortund commented on lib/media_types/scheme.rb
> +          failed_fixtures << e.message
Updated

2021-02-15 17:57 UTC, Dortund commented on lib/media_types/scheme.rb
> +          failed_fixtures += e.fixture_errors
It now properly is, yes.

2021-02-15 17:57 UTC, Dortund commented on lib/media_types/scheme.rb
> +    def run_fixture_validations(expect_symbol_keys, backtrace = [])
Updated.

2021-02-15 17:57 UTC, Dortund commented on lib/media_types/scheme.rb
> +      json = JSON.parse(fixture_data.fixture, { symbolize_names: expect_symbol_keys })
Updated.

2021-02-15 17:58 UTC, Dortund commented on lib/media_types/scheme.rb
> +        unless fixture_data.expect_to_pass
Fixed.

2021-02-15 17:58 UTC, Dortund commented on lib/media_types/scheme.rb
> +          message = (fixture_data.caller.path + ':' + fixture_data.caller.lineno.to_s + ' -> No error encounterd whilst expecting to').to_s
Message generation has been moved to the error class itself.

2021-02-15 17:59 UTC, Dortund commented on lib/media_types/scheme/links.rb
> +              failed_fixtures += e.fixture_errors
Updated.

2021-02-15 18:43 UTC, Dortund commented on test/media_types/key_type_expectations_test.rb
> +    #                    ---------->NoKeyTypeSpecified
Incorrect how? Is the formatting confusing or the data?

2021-02-15 18:45 UTC, VincentRbbmnd commented on test/test_helper.rb
> +    include MediaTypes::Assertions
At this point it does not anymore, people have to explicitly include this module

2021-02-15 18:51 UTC, thexa4 requested changes

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +If the MediaTypes you create enforce a specification you _do not expect them to_ it will cause problems that will be very difficult to fix, as other code which utilises
Missing text?

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +Well, during this time, your users started to write code which conformed to the specification outlined by the faulty MediaType. So, it's going to be extreamly difficult to revert your mistake.
Typo

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +3. The library automatically check a MediaType's checks defined by (1) the first time it is validated, and throw an error if any fail.
What does it mean when you check checks?

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +4. The library provides you with a way to run the checks carried out by (3) on load, using the method [`assert_sane`](README.md#validation-checks) so that your server will not run should any of the c
Shouldn't this be `assert_sane!`?

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +The library provides the `assert_mediatype_specification` method, which allows running the checks for a particular `MediaType` within Minitest with `assert_pass` and `assert_fail`. In order to use `a
Where should you include this?

2021-02-15 18:51 UTC, thexa4 commented on README.md
> +The example below demonstrates how to use `assert_pass` and `assert_fail` within a MediaType, and how to use the `assert_mediatype_specification` method in MiniTest tests to validate them.
Wasn't this renamed?

2021-02-15 19:11 UTC, Dortund commented on README.md
> +If the MediaTypes you create enforce a specification you _do not expect them to_ it will cause problems that will be very difficult to fix, as other code which utilises
Updated

2021-02-15 19:11 UTC, Dortund commented on README.md
> +Well, during this time, your users started to write code which conformed to the specification outlined by the faulty MediaType. So, it's going to be extreamly difficult to revert your mistake.
Updated

2021-02-15 19:11 UTC, Dortund commented on README.md
> +4. The library provides you with a way to run the checks carried out by (3) on load, using the method [`assert_sane`](README.md#validation-checks) so that your server will not run should any of the c
Updated

2021-02-15 19:11 UTC, Dortund commented on README.md
> +3. The library automatically check a MediaType's checks defined by (1) the first time it is validated, and throw an error if any fail.
Updated

2021-02-15 19:11 UTC, Dortund commented on README.md
> +The library provides the `assert_mediatype_specification` method, which allows running the checks for a particular `MediaType` within Minitest with `assert_pass` and `assert_fail`. In order to use `a
Updated

2021-02-15 19:11 UTC, Dortund commented on README.md
> +The example below demonstrates how to use `assert_pass` and `assert_fail` within a MediaType, and how to use the `assert_mediatype_specification` method in MiniTest tests to validate them.
Updated

2021-02-15 19:16 UTC, SleeplessByte commented on test/media_types/key_type_expectations_test.rb
> +    #                    ---------->NoKeyTypeSpecified
![image](https://user-images.githubusercontent.com/1964376/107985557-96434500-6fca-11eb-8206-ada6ebc0a123.png)

It looks completely misaligned, and even together with the description it doesn't really make sense what I'm looking at.

2021-02-15 19:38 UTC, Dortund commented on test/media_types/key_type_expectations_test.rb
> +    #                    ---------->NoKeyTypeSpecified
Updated

2021-02-15 19:39 UTC, Dortund commented on lib/media_types/scheme.rb
> +      reduced_stack = caller_locations.filter { |location| !location.path.include?(__dir__) }
Updated

2021-02-15 19:41 UTC, Dortund commented on README.md
> +
Louis says he updated it

2021-02-15 21:10 UTC, SleeplessByte requested changes
I expected this to be ready, as said on the call and on voice after. A lot of time was spent on grammar and spelling. I think that a lot of that could have been avoided if there was more time spent double-checking what's on the PR.

I have the feeling that the changes were not peer-reviewed, making me responsible (taking on that work) of peer-review. If this is the case, I strongly suggest to start peer-reviewing from now on.

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      if @error.is_a?(MediaTypes::Scheme::ValidationError)
Use string formatting and/or interpolation.

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @fixtureCaller = fixtureCaller
These are accessors, so should be `self.fixtureCaller`

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    end
```suggestion
      fixture_errors.map(&:message).join(', ')
    end
```

I think this is what ya meant.

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      if @error.is_a?(MediaTypes::Scheme::ValidationError)
All these `@xxx` are accessors, so should be accessed through their getter.

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      @expect_to_pass = expect_to_pass
Same as above

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    attr_accessor :caller, :fixture, :expect_to_pass
```suggestion
    attr_accessor :caller, :fixture, :expect_to_pass
    
    alias expect_to_pass? expect_to_pass
```

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    end
```suggestion
    alias asserted_sane? asserted_sane
```

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      type ||= ::Object
Why was this changed from the initializer in the method param?

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      }.flatten.compact
perhaps `flat_map` would have worked?

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      return []
```suggestion
      []
```

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      return e.fixture_errors
```suggestion
      e.fixture_errors
```

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +    def run_fixture_validations(expect_symbol_keys, backtrace = [])
Much much better. Thanks!

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme/links.rb
> +        }.flatten.compact
flat_map

2021-02-15 21:10 UTC, SleeplessByte commented on lib/media_types/scheme/rules_exhausted_guard.rb
> +              ) unless key.class == options.expected_key_type || rules.get(key).class == NotStrict
Multine `unless` are confusing. Instead wrap the entire `raise` with the `unless`.

2021-02-15 22:05 UTC, Dortund commented on lib/media_types/scheme.rb
> +      type ||= ::Object
The preceding if check on the raise can't check if type equals ::Object, because it is possible for the user to supply that as an actual argument. And we don't want it to break in that case

2021-02-15 22:13 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      type ||= ::Object
But type will never be nil in that case?

2021-02-15 22:17 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
>                raise format('Implement the class method "organisation" in %<klass>s or specify a global organisation using MediaTypes::set_organisation', klass: self) if resolved_org.nil?
This already exists in `master`, I'm not aware of the decision regarding this way of raising without custom error.

2021-02-15 22:20 UTC, Dortund commented on lib/media_types/scheme.rb
> +      return e.fixture_errors
Fixed

2021-02-15 22:20 UTC, Dortund commented on lib/media_types/scheme.rb
> +      return []
fixed

2021-02-15 22:20 UTC, Dortund commented on lib/media_types/scheme.rb
> +      }.flatten.compact
Updated

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +    end
Updated, as well as lacking an asserted_sane getter, but do having a public writer. Made the writer private and a public getter.

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +    attr_accessor :caller, :fixture, :expect_to_pass
Updated

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +      @expect_to_pass = expect_to_pass
Updated

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +      if @error.is_a?(MediaTypes::Scheme::ValidationError)
Updated

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +      if @error.is_a?(MediaTypes::Scheme::ValidationError)
Updated

2021-02-15 22:21 UTC, Dortund commented on lib/media_types/scheme.rb
> +      @fixtureCaller = fixtureCaller
Updated

2021-02-15 22:22 UTC, VincentRbbmnd commented on lib/media_types/dsl.rb
> +        raise "No validations defined for #{name}" if media_type_validations.nil?
Same as for the other `raise` without custom error only this line is tagged as added because it got extracted into a new function.

2021-02-15 22:25 UTC, VincentRbbmnd commented on lib/media_types/minitest/assert_mediatype.rb
> +module MediaTypes
This was implemented the same way as the existing custom assertion for consistency

2021-02-15 22:26 UTC, Dortund commented on lib/media_types/scheme/rules_exhausted_guard.rb
> +              ) unless key.class == options.expected_key_type || rules.get(key).class == NotStrict
Updated

2021-02-15 22:30 UTC, Dortund commented on lib/media_types/scheme.rb
> +      type ||= ::Object
It should be when the user provides a block.

2021-02-15 22:38 UTC, Dortund commented on lib/media_types/scheme.rb
> +      type ||= ::Object
When an user provides a block to 'attribute', any given type is ignored. It was decided that doing so silently could cause confusion, so we want to raise an error (when the user gives both a block and a type).
If we set the default of type to 'Object', we must write an 'if' that checks if type != Object to detect if the user entered a type. However, 'Object' could be a valid type that the user could enter, so we changed the default to be nil (still something the user could enter, but would make much less sense to do so).
Now we're left with the fact that type is an optional parameter. So 'attribute :foo' should add the same rule as it did previously. With the default being now 'nil', that is no longer the case, so we should update the default to 'Object'

2021-02-15 23:16 UTC, louisraymond commented on lib/media_types/minitest/assert_media_type_format.rb
>    module Assertions
Existing code, We think it's not in scope of current PR, should make an issue about it

2021-02-15 23:17 UTC, VincentRbbmnd commented on lib/media_types/minitest/assert_media_type_format.rb
>    module Assertions
This is already on `master`, I'm unaware as to why this is implemented the way it is. We can make an issue for this if this needs to be adressed

2021-02-15 23:24 UTC, louisraymond commented on README.md
> +For this reason,it is vital that when using this library, your MediaTypes enforce the _correct_ specification, as the rules they enforce will significantly impact code elsewhere in your codebase. To
If the MediaTypes you create enforce a specification you _do not expect them to_, it will cause problems that will be very difficult to fix, as other code, which utilises your MediaType, would break when you change the specification. This is because the faulty MediaType definition will start to make other code dependent on the specification it defined.

For example, consider what would happen if you release a MediaType which defines an attribute `foo` to be a `String`, and run a server which define such a specification. Later, you realise you _actually_ wanted `foo` to be `Numeric`. What can you do?

Well, during this time, other people started to write code which conformed to the specification defined by the faulty MediaType. So, it's going to be extremely difficult to revert your mistake.

For this reason, it is vital that, when using this library, your MediaTypes define the _correct_ specification.

To this end, we provide you with a few avenues to check whether MediaTypes define the specifications you actually intend by checking examples of JSON you expect to be compliant/non-compliant with the MediaType definitions you write out.

2021-02-15 23:24 UTC, louisraymond commented on README.md
> +For this reason,it is vital that when using this library, your MediaTypes enforce the _correct_ specification, as the rules they enforce will significantly impact code elsewhere in your codebase. To
I wrote the snippet above to try and hit those three points

2021-02-16 15:04 UTC, SleeplessByte commented on lib/media_types/scheme.rb
> +      type ||= ::Object
Got it. That's fine then.

2021-02-16 15:12 UTC, SleeplessByte requested changes
Please manually re-check all the previous comments. There are formatting issues marked as resolved; there might be "content" issues, but I don't think it's good for me to spend time on what I expect you to do (double checking the PR before it's said "to be ready").

2021-02-16 15:12 UTC, SleeplessByte commented on README.md
> +
This was marked as resolved but it isn't.

2021-02-16 17:00 UTC, VincentRbbmnd commented on README.md
> +Key type expectations can also be set at the module level, each MediaType within this module will inherit the expectation set by that module.
Setting the key type expectation in the module is the first example, then it is shown how to override that by setting it within a MediaType class

2021-02-17 15:34 UTC, Dortund commented on lib/media_types/dsl.rb
>                raise format('Implement the class method "organisation" in %<klass>s or specify a global organisation using MediaTypes::set_organisation', klass: self) if resolved_org.nil?
Custom error added

2021-02-17 15:34 UTC, Dortund commented on lib/media_types/dsl.rb
> +        raise "No validations defined for #{name}" if media_type_validations.nil?
Custom error added

2021-02-19 15:02 UTC, SleeplessByte commented on README.md
> +
This is not resolved?

2021-02-19 15:02 UTC, SleeplessByte commented on lib/media_types/dsl/errors.rb
> +        'Unable to generate constructable without a name, have you called `use_name(name)`?'
Instead of asking a question, tell them what to do.

2021-02-19 15:48 UTC, Dortund commented on README.md
> +    # "Any" means there are no required keys, so having no keys should also pass
Code block updated

2021-02-19 15:48 UTC, Dortund commented on README.md
> +    # as indicated by "Numeric" at the top of the block
Code block updated

2021-02-19 15:48 UTC, Dortund commented on README.md
> +    # but, it does care that those keys point to a Numeric value,
Code block updated

2021-02-19 17:10 UTC, VincentRbbmnd commented on README.md
> +When interacting with Ruby objects defined by your MediaType, you want to avoid having them looking up a value and getting `nil`, just because they used the wrong key type. To this end, the library p
Updated

2021-02-19 17:11 UTC, VincentRbbmnd commented on README.md
> +
The examples were in a section below, but moved a relevant example up here.

2021-02-19 17:11 UTC, VincentRbbmnd commented on lib/media_types/dsl/errors.rb
> +        'Unable to generate constructable without a name, have you called `use_name(name)`?'
Updated to be more imperative

2021-02-19 17:29 UTC, Dortund commented on README.md
> +    # default attribute type is a Hash
Updated the README to use Hash explicitly. This means I also updated when the error is thrown that prevents a user from providing both a type and a block to the rule. Hash is now allowed as a type, and the error message is updated to indicate that problems occur when you try to mix a block and a non-hash type, which is closer in describing the original problem. Added bonus of having less chance to break existing code.

2021-02-22 00:17 UTC, SleeplessByte approved these changes

2021-02-22 00:19 UTC, merged